FROM python:3.11-slim

# 1) Instalamos dependencias de sistema para lxml
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      build-essential \
      libxml2-dev \
      libxslt1-dev \
      && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# 2) Copiamos y pip install
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# 3) Copiamos el resto del scraper
COPY . .

EXPOSE 4002
CMD ["python", "app.py"]
