FROM python:3.11-slim

# Instalar dependencias del SO para Playwright
RUN apt-get update && apt-get install -y \
    wget \
    gnupg \
    ca-certificates \
    libgtk-3-0 \
    libdbus-glib-1-2 \
    libx11-xcb1 \
    libnss3 \
    libasound2 \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Descargar navegadores para Playwright
RUN playwright install --with-deps chromium

COPY . .
EXPOSE 4002
CMD ["python", "app.py"]
