# Usa una imagen de Python como base
FROM python:3.11-slim

# Configura el directorio de trabajo
WORKDIR /app

# Copia los archivos de tu frontend
COPY requirements.txt ./
RUN pip install -r requirements.txt

# Copia el código de tu frontend
COPY . .

# Ejecuta el servidor Flask
CMD ["python", "app.py"]

